Add unit tests for divide_and_conquer() - issue 92
arcosuc3m/grppi pull request #131
Opened 2017-06-22 15:00 UTC by AndresSanchezCuadrado

Unit test divide and conquer static and polymorphic.

2017-06-23 06:36 UTC, jdgarciauc3m requested changes
Remove anything related to polymorphic_execution. That will be handled separately as part of issue #90

2017-06-23 08:04 UTC, jdgarciauc3m commented on unit_tests/divideandconquer.cpp
> +      // Divide
Move comment before lambda start

2017-06-23 08:05 UTC, jdgarciauc3m commented on unit_tests/divideandconquer.cpp
> +      std::vector<std::vector<int> > subproblem;
Collapse in return std::vector<std::vector<int>>{};

2017-06-23 08:06 UTC, jdgarciauc3m commented on unit_tests/divideandconquer.cpp
> +      // Base
Comment before lambda start. Change comment to "solve base case"

2017-06-23 08:06 UTC, jdgarciauc3m commented on unit_tests/divideandconquer.cpp
> +    [this](auto & partial, auto & out) {
Comment before lambda start. "Combine"

2017-06-23 08:11 UTC, jdgarciauc3m commented on unit_tests/divideandconquer.cpp
> +      std::vector<std::vector<int>> subproblem;
return vector<vector<int>> {v};

2017-06-23 08:13 UTC, jdgarciauc3m commented on unit_tests/divideandconquer.cpp
> +      std::vector<std::vector<int>> subproblem;
return vector<vector<int>> {begin(v), end(v)};

2017-06-23 08:13 UTC, jdgarciauc3m requested changes
Address comments.

2017-06-28 07:12 UTC, AndresSanchezCuadrado commented
Requires to be updated after merged branch of issue 123

2017-06-28 07:47 UTC, jdgarciauc3m commented
Issue #123 has already been solved by merging PR #160 to latest

2017-06-28 10:41 UTC, jdgarciauc3m commented
Remove tests that are no longer compiling after modifying from directory `legacy_utest`

2017-06-28 11:19 UTC, jdgarciauc3m approved these changes
OK

2017-06-28 11:19 UTC, merged

2017-06-28 11:19 UTC, jdgarciauc3m commented
Solves issue #92