Add unit tests for pipeline() - issue 95
arcosuc3m/grppi pull request #134
Opened 2017-06-22 16:14 UTC by AndresSanchezCuadrado

Unit tests pipeline

2017-06-23 06:31 UTC, jdgarciauc3m commented on unit_tests/pipeline.cpp
> +  polymorphic_execution poly_execution_ =
Remove poly execution testing. We will handle this as part of issue-90

2017-06-23 06:33 UTC, jdgarciauc3m commented on unit_tests/pipeline.cpp
> +TYPED_TEST(pipeline_test, poly_empty)
Remove all the poly_* test cases. We will add them as part of issue #90

2017-06-23 06:35 UTC, jdgarciauc3m requested changes
Remove anything related to polymorphic_execution from this test. That will be handled separately with issue #90

2017-06-23 08:17 UTC, jdgarciauc3m requested changes
Reorganize test cases.

As a minimum I see:

* Pipeline with 0 stages (zero_stages)
* Pipeline with 1 stage (one_stage)
* Pipeline wiht 2 stages (two_stages)
* Pipeline with 3 stages (three_stages)

2017-06-27 15:27 UTC, AndresSanchezCuadrado commented
For this unit test to work, the issue 176 needs to be merged with latest.

2017-06-27 15:28 UTC, AndresSanchezCuadrado commented on unit_tests/pipeline.cpp
> +          //this->invocations_intermediate++;
Problem with scope. If this is uncommented a segmentation fault is produced.

2017-06-28 12:43 UTC, jdgarciauc3m commented on unit_tests/pipeline.cpp
> +          //this->invocations_intermediate++;
This needs to be debugged and solved.

A core is generated with native and TBB.

2017-06-28 16:09 UTC, jdgarciauc3m approved these changes
OK

2017-06-28 16:09 UTC, merged

2017-06-28 16:10 UTC, jdgarciauc3m commented
Solves issue #95