Revised reduce interface
arcosuc3m/grppi pull request #149
Opened 2017-06-23 15:21 UTC by Drioastorga

Modified reduce interface.

Changes:
- Reduce interface versions targeted to iterable outputs have been removed. 
- Modified interface. Now the reduce supports any reduce operation (lamda or standard binary operators) and receive an initial (identity) value for those operations that cannot be deduced. Alternatively, there is a new interface that does not recieve any initial value but computes the identity value if the input types can be casted to boolean. Note that the reduce interface only supports homogeneous reduce operations, i.e T x = op(T y, Y z) being T the container value type.
- Updated test to match with the new interface.

2017-06-24 09:44 UTC, jdgarciauc3m commented on include/native/reduce.h
> +*te < typename InputIt, typename ReduceOperator>
I imagine this is a mistake. What's the point of this in the middle of the license?

2017-06-24 09:50 UTC, jdgarciauc3m requested changes
Anything that can be forwarded sould be a forwarding reference argument.

In general, make all function object arguments forwarding references.

2017-06-26 07:34 UTC, Drioastorga commented on include/native/reduce.h
> +*te < typename InputIt, typename ReduceOperator>
It was a mistake. I have removed those lines.

2017-06-26 07:42 UTC, Drioastorga reviewed
I have modified the reduce interface to pass the function objects as forwarding references.

2017-06-26 08:14 UTC, jdgarciauc3m commented on include/native/mapreduce.h
> +       *firstOut = reduce(p, mapresult.begin(), mapresult.end(), op);
You need to forward op here

2017-06-26 08:19 UTC, jdgarciauc3m commented on include/native/reduce.h
> +reduce(parallel_execution_native &p, InputIt first, InputIt last, typename std::iterator_traits<InputIt>::value_type init, ReduceOperator && op){
In all grppi::reduce the operation type should be renamed to `Combiner` and the argument to `combine_op`.

In all grppi::map_reduce the operation type should be renamed to `Transformer` and the argument to `transform_op`.

2017-06-26 08:20 UTC, jdgarciauc3m commented on include/native/reduce.h
> +//typename ReduceOperator::result_type
What are this comments for?

2017-06-26 08:21 UTC, jdgarciauc3m requested changes
I made some comments. Try to address them generally.

2017-06-26 12:55 UTC, Drioastorga commented on include/native/reduce.h
> +//typename ReduceOperator::result_type
These comments have been removed.

2017-06-26 13:38 UTC, Drioastorga commented on include/native/reduce.h
> +reduce(parallel_execution_native &p, InputIt first, InputIt last, typename std::iterator_traits<InputIt>::value_type init, ReduceOperator && op){
Type and function object names have been acordingly modified in reduce and map_reduce interfaces.

2017-06-26 13:39 UTC, Drioastorga commented on include/native/mapreduce.h
> +       *firstOut = reduce(p, mapresult.begin(), mapresult.end(), op);
Fixed.

2017-06-26 13:42 UTC, Drioastorga reviewed
Types and function objects names have been modified.

2017-06-28 10:13 UTC, jdgarciauc3m commented on include/native/mapreduce.h
> +            partialOuts[i] = MapReduce(sequential_execution{}, begin, last, std::forward<Transformer>(transform_op), std::forward<Combiner>(combine_op));
What is MapReduce calling to?
Is this really used?

2017-06-28 10:14 UTC, jdgarciauc3m commented on include/native/mapreduce.h
> +    Reduce(sequential_execution{}, partialOuts.begin(), partialOuts.end(), out, std::forward<Combiner>(combine_op));
What is this Reduce() calling to?

2017-06-28 10:15 UTC, jdgarciauc3m requested changes
Address comments.

Besides building of this branch fails

[ 85%] Building CXX object legacy_utest/CMakeFiles/divideandconquer1_GT.dir/divideandconquer1_GT.cpp.o
/home/jdgarcia/github-repos/arcosuc3m/grppi/legacy_utest/reduce2_GT.cpp: In instantiation of ‘int reduce_example2(auto:1&) [with auto:1 = grppi::sequential_execution]’:
/home/jdgarcia/github-repos/arcosuc3m/grppi/legacy_utest/reduce2_GT.cpp:65:5:   required from here
/home/jdgarcia/github-repos/arcosuc3m/grppi/legacy_utest/reduce2_GT.cpp:53:12: error: no matching function for call to ‘reduce(grppi::sequential_execution&, std::vector<std::vector<int> >::iterator, std::vector<std::vector<int> >::iterator, std::vector<int>::iterator, reduce_example2(auto:1&) [with auto:1 = grppi::sequential_execution]::<lambda(auto:2&, auto:3&)>)’
      reduce(p, in.begin(), in.end(), out.begin(), [&](auto & in, auto & out){
      ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              reduce(p, in.begin(), in.end(), out,  std::plus<int>() );
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          }
          ~  
      );
      ~      
In file included from /home/jdgarcia/github-repos/arcosuc3m/grppi/include/reduce.h:28:0,

2017-06-28 12:30 UTC, Drioastorga commented
The changes of the mapreduce should be addressed for the issue 122. I will take these comments into account for the aforementioned issue.

2017-06-28 15:56 UTC, jdgarciauc3m approved these changes
OK

2017-06-28 15:56 UTC, merged

2017-06-28 15:56 UTC, jdgarciauc3m commented
Solves issue #121