Add unit tests for stream_reduce() - issue 100
arcosuc3m/grppi pull request #150
Opened 2017-06-23 15:44 UTC by AndresSanchezCuadrado

unit test stream_reduce

2017-06-24 09:52 UTC, jdgarciauc3m commented on unit_tests/stream_reduce.cpp
> +/*
Remove comments before merge

2017-06-24 09:53 UTC, jdgarciauc3m commented on unit_tests/stream_reduce.cpp
> +    [this]() {
[this]() -> optional<int> {
  this->invocations++;
  return {};
}

2017-06-24 09:55 UTC, jdgarciauc3m reviewed
In genera the test cases need to be discussed in the next developers meeting.

2017-06-26 08:22 UTC, jdgarciauc3m commented on unit_tests/stream_reduce.cpp
> +    [this]() {
This has not been addressed.

2017-06-26 08:23 UTC, jdgarciauc3m requested changes
Adress remaining comments.
Try to name test cases with meaningful names. If needed add some comment.

2017-06-26 13:05 UTC, AndresSanchezCuadrado commented
It has not been fully tested. It has a dependency with another issue, as soon as it is solved we could test this one.

2017-06-26 13:52 UTC, jdgarciauc3m commented
Please, document which issue we depend on.

2017-06-27 07:36 UTC, AndresSanchezCuadrado commented
Depends on issue 127: Revise stream_reduce().

2017-06-28 13:50 UTC, jdgarciauc3m commented
This branch does not compile.

2017-06-29 15:01 UTC, jdgarciauc3m approved these changes
OK

2017-06-29 15:01 UTC, merged

2017-06-29 15:01 UTC, jdgarciauc3m commented
Solves issue #100