Renamed NextInputs and GetStart by advance_iterators - issue 152
arcosuc3m/grppi pull request #154
Opened 2017-06-26 08:17 UTC by AndresSanchezCuadrado

Renamed NextInputs and GetStart function names by advance_iterators.

2017-06-26 08:31 UTC, jdgarciauc3m commented on include/native/reduce.h
> +        advance_iterators( inputs... );
Is this fixing a commented code?

2017-06-26 08:31 UTC, jdgarciauc3m commented on include/native/mapreduce.h
> +        advance_iterators( inputs... );
Is this fixing commented code?

2017-06-26 08:32 UTC, jdgarciauc3m commented on include/native/stencil.h
> +               advance_iterators(n, i, inputs ...);
This needs to be reviewed by  @Drioastorga

2017-06-26 08:32 UTC, jdgarciauc3m commented on include/omp/divideandconquer.h
> +        advance_iterators( inputs... );
Fixing commented code?

2017-06-26 08:32 UTC, jdgarciauc3m commented on include/omp/reduce.h
> +        advance_iterators( inputs... );
Fixing commented code?

2017-06-26 08:33 UTC, jdgarciauc3m commented on include/omp/stencil.h
> +           advance_iterators(elemperthr, i, inputs ...);
Needs to be reviewed by @Drioastorga

2017-06-26 08:33 UTC, jdgarciauc3m commented on include/seq/divideandconquer.h
> +        advance_iterators( inputs... );
Fixing commented code?

2017-06-26 08:33 UTC, jdgarciauc3m commented on include/seq/mapreduce.h
> +        advance_iterators( inputs... );
Fixing commented code?

2017-06-26 08:33 UTC, jdgarciauc3m commented on include/seq/reduce.h
> +        advance_iterators( inputs... );
Fixing commented code?

2017-06-26 08:34 UTC, jdgarciauc3m requested changes
In many cases we are updating commented out code, that needs to be removed anyway.

In general we need that @Drioastorga reviews the change-set.

2017-06-26 15:10 UTC, jdgarciauc3m requested changes
I still see a lot of modifications to commented code.

This sould not be part of this pull-request.

2017-06-26 15:42 UTC, jdgarciauc3m commented
Added @Drioastorga as additional reviewer of this PR. We will wait his approval for merge.

2017-06-27 21:12 UTC, jdgarciauc3m commented
Still this needs review by @Drioastorga

2017-06-28 07:45 UTC, Drioastorga approved these changes
It works perfectly and the changes are right.

2017-06-28 10:20 UTC, jdgarciauc3m approved these changes

2017-06-28 10:20 UTC, jdgarciauc3m commented
Solves issue #152

2017-06-28 10:20 UTC, merged