Revised mpmc_queue constructor interface - issue 118
arcosuc3m/grppi pull request #157
Opened 2017-06-26 14:13 UTC by Drioastorga

The default mode for the mpmc_queue have been removed.

2017-06-26 15:22 UTC, jdgarciauc3m commented on include/common/mpmc_queue.h
> +      mpmc_queue<T>(int _size, queue_mode active):
change argument name to something different from `active` which is no longer meaningful.

Perhaps mode?

2017-06-26 15:22 UTC, jdgarciauc3m requested changes
See code comment.

2017-06-27 07:42 UTC, Drioastorga commented on include/common/mpmc_queue.h
> +      mpmc_queue<T>(int _size, queue_mode active):
This argument have been renamed to "q_mode". Aditionally, the "_size" argument have been renamed to "q_size".

2017-06-27 20:21 UTC, jdgarciauc3m requested changes
This does not compile. Please review.

2017-06-28 08:11 UTC, Drioastorga commented
Solved. It was a mistake in the last commit and push.

2017-06-28 10:47 UTC, jdgarciauc3m approved these changes
OK

2017-06-28 10:48 UTC, jdgarciauc3m commented
Solves issue #118

2017-06-28 10:49 UTC, merged