Add links from doc main page to individual patterns documentation - Issue 161
arcosuc3m/grppi pull request #163
Opened 2017-06-26 16:54 UTC by jdgarciauc3m

2017-06-27 09:35 UTC, Drioastorga requested changes
Links in the main page to the patterns related pages does not work. These links references to <pattern>.md files that does not exists or they are not in the right place.

2017-06-28 14:46 UTC, jdgarciauc3m commented
This is a known issue of doxygen. Will be solved in a future release.

2017-06-28 17:05 UTC, jdgarciauc3m commented
We may set a workaround in the CMake file at doxy directory

For every file of the form md_*.html, copy it to the correspondig *_8md.html

2017-06-30 16:31 UTC, merged

2017-06-30 16:32 UTC, jdgarciauc3m commented
Solves issue #161