Full review of map pattern documentation - Issue 164
arcosuc3m/grppi pull request #173
Opened 2017-06-26 22:55 UTC by jdgarciauc3m

Revised fully the documentation of map in mark-down.

Revised documentation for map API in all headers.

Slightly reworked code.

2017-06-27 07:29 UTC, AndresSanchezCuadrado reviewed
Documentation understandable and changes in the map files allow a correct compilation.

2017-06-27 09:21 UTC, Drioastorga requested changes
It's necessary to modify the unary map example to match with the description.

2017-06-27 09:21 UTC, Drioastorga commented on doc/map.md
> +**Example**: Squaring values in a vector.
The example doubles the values in the vector instead of square them. 

The description or the example should be modified .

2017-06-28 16:16 UTC, javidoc00 approved these changes
OK

2017-06-28 16:16 UTC, mdolz approved these changes
OK

2017-06-29 07:58 UTC, Drioastorga approved these changes

2017-06-29 07:59 UTC, merged

2017-06-29 08:00 UTC, jdgarciauc3m commented
Solves issue #164