Full review of reduce documentation - Issue 169
arcosuc3m/grppi pull request #203
Opened 2017-06-29 22:55 UTC by jdgarciauc3m

Reviewed all documentation of reduce.
Also simplified the interface.

2017-06-30 15:33 UTC, Drioastorga requested changes
I have some comments about the reduce documentation that have to be addressed. Additionally, I have an issue for viewing the "collaboration diagram" of the different actual implementations of patterns. I don't know if is a real issue or is my browser but it shows a broken link to an image.

2017-06-30 15:33 UTC, Drioastorga commented on doc/reduce.md
> +* **Sequence reduction without initial value**: Reduces a sequence of values
I think that this is not true anymore. Now, this interface allways requires the identity value.  This applies also for its description.

2017-06-30 15:33 UTC, Drioastorga commented on doc/reduce.md
> +An **HomogeneousCombiner** `cmb` is any operatingo taking two values `x`and `y`
operatingo -> operation

2017-06-30 15:33 UTC, Drioastorga commented on doc/reduce.md
> +An **HeterogeneousCombiner** `cmb` is any operations taking two values `x` and
I think that it should be in singular: 
operations -> operation

2017-06-30 15:33 UTC, Drioastorga commented on doc/reduce.md
> +### Sequence reducction without identity
This subsection should be removed as this interface is not supported in the current version.

2017-06-30 16:44 UTC, jdgarciauc3m commented on doc/reduce.md
> +* **Sequence reduction without initial value**: Reduces a sequence of values
You are right!

2017-06-30 16:45 UTC, jdgarciauc3m commented on doc/reduce.md
> +An **HomogeneousCombiner** `cmb` is any operatingo taking two values `x`and `y`
OK

2017-06-30 16:45 UTC, jdgarciauc3m commented on doc/reduce.md
> +An **HeterogeneousCombiner** `cmb` is any operations taking two values `x` and
OK

2017-07-03 07:58 UTC, Drioastorga approved these changes

2017-07-03 11:14 UTC, merged

2017-07-03 11:15 UTC, jdgarciauc3m commented
Solves issue #169