Changed grppi:optional to std::experimental::optional  - issue 88
arcosuc3m/grppi pull request #211
Opened 2017-07-03 13:40 UTC by Drioastorga

I have modified grppi to use internally the experimental optional insted of the grppi's optional. 

Changes:
- Removed grppi optional.
- Modified uses of optional to std::experimental::optional.

2017-07-04 14:20 UTC, jdgarciauc3m commented on include/common/common.h
> +#include <experimental/optional>
I do not think we need to include optional here in any form.

Just include in the places we really use it.

2017-07-04 14:22 UTC, jdgarciauc3m commented on tests/farm1.cpp
> +                return std::experimental::optional<int>();
Add a:

template <typename T>
using optional = std::experimental::optional<T>;

before call ing farm.

2017-07-04 14:23 UTC, jdgarciauc3m commented on tests/farm1.cpp
> +                return std::experimental::optional<int>();
Declare the lambda as

~~~
[&a]() -> optional<int> {
  a--;
  if (a==0} return {}
  else return a;
}
~~~

2017-07-04 14:26 UTC, jdgarciauc3m commented on unit_tests/map.cpp
> +#include <experimental/optional>
Why do we need to include optiona here?

2017-07-04 14:29 UTC, jdgarciauc3m requested changes
General comments:

1. Simplify code by typedefs (with using syntax) in places like implementations of farm.

2. Be explicit about lambdas by stating return type. In this way we avoid to write verbose code.

2017-07-05 09:17 UTC, Drioastorga commented on include/common/common.h
> +#include <experimental/optional>
Removed from here and included only in the patterns that really need it.

2017-07-05 09:17 UTC, Drioastorga commented on tests/farm1.cpp
> +                return std::experimental::optional<int>();
Modified in all tests and unit tests.

2017-07-05 09:18 UTC, Drioastorga commented on unit_tests/map.cpp
> +#include <experimental/optional>
Removed as it is no tnecessary.

2017-07-05 09:27 UTC, Drioastorga commented
I have addresed all the comments but i did not change the use of fully qualified names in the pattern implementations, only in the tests. 

The main reason is that a template can not be defined inside a block, so it has to be declared out of the funcion. Therefore only one declaration of the typedef is allowed, otherwise it will be ambiguous. Even if we define it only once in the grppi code, if the user also define the same it will be ambiguous too.

2017-07-05 11:06 UTC, jdgarciauc3m commented on include/native/pipeline.h
> +#define GRPPI_PIPELINE_THR_Hi
What is this change?

2017-07-05 11:24 UTC, jdgarciauc3m requested changes
Address minor comment on include guard.

2017-07-05 12:43 UTC, Drioastorga commented
Fixed include guard.

2017-07-05 12:53 UTC, jdgarciauc3m approved these changes
OK

2017-07-05 12:53 UTC, merged

2017-07-05 12:53 UTC, jdgarciauc3m commented
Solves issue #88