Full review of farm - Issue 166
arcosuc3m/grppi pull request #234
Opened 2017-07-14 20:47 UTC by jdgarciauc3m

Revised all documentation and code of farm.

Also added new example that capitalizes text.

2017-07-17 10:12 UTC, mdolz requested changes
Changes requested are inlined in the codes.

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
> +generator produces values of any type that is convertible to `bool` and can
Replace: `and can dereferenced` -> `which can be dereferenced`

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
>  **Example**
Forgotten description for the example: `**Example:** Composed pipeline ...`

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
>  **Example**
Forgotten description for the example: `**Example:** Composed pipeline ...`

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
>  **Note**: For brevity we do not show here the details of other stages.
This note does not follow the same MD format as you used for the filter pattern.

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
>  **Note**: For brevity we do not show here the details of other stages.
This note does not follow the same MD format as you used for the filter pattern.

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
>  farm(exec,
Forgotten `grppi::` qualified name for the `farm` function.

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
>  pipeline(exec,
Forgotten `grppi::` qualified name for the `pipeline` function.

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
> +  farm(exec, [](auto x) {
Forgotten `grppi::` qualified name for the `farm` function.

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
> +auto print_long_words = farm(exec, [](auto x) {
Forgotten `grppi::` qualified name for the `farm` function.

2017-07-17 10:12 UTC, mdolz commented on doc/farm.md
>  pipeline(exec,
Forgotten `grppi::` qualified name for the `pipeline` function.

2017-07-17 10:20 UTC, javidoc00 requested changes
changes are inline

2017-07-17 10:20 UTC, javidoc00 commented on doc/farm.md
>      if (file) return word;
In line 96 file variable should be passed by value or reference to the lambda function.

2017-07-17 15:13 UTC, jdgarciauc3m commented on doc/farm.md
>      if (file) return word;
It needs to be by reference.

2017-07-17 15:18 UTC, jdgarciauc3m commented on doc/farm.md
> +generator produces values of any type that is convertible to `bool` and can
Solved by commit 223a37b6d630d856ce55831446c30e8e09403f75

2017-07-17 15:18 UTC, jdgarciauc3m commented on doc/farm.md
>      if (file) return word;
Solved by commit 223a37b6d630d856ce55831446c30e8e09403f75

2017-07-20 07:53 UTC, mdolz submitted a review, later dismissed

2017-07-20 07:55 UTC, Drioastorga submitted a review, later dismissed
Ok

2017-07-20 09:04 UTC, javidoc00 approved these changes

2017-07-20 09:07 UTC, merged

2017-07-20 09:08 UTC, jdgarciauc3m commented
Closes issue #166