Full review of map/reduce documentation - Issue 167
arcosuc3m/grppi pull request #248
Opened 2017-07-19 13:30 UTC by jdgarciauc3m

2017-07-19 14:13 UTC, mdolz requested changes
changes requested are inline.

2017-07-19 14:13 UTC, mdolz commented on doc/map-reduce.md
> +extra optimizations.
Replace `stages allowing for extra optimizations` by `stages, thus allowing for further optimizations`.

2017-07-19 14:13 UTC, mdolz commented on doc/map-reduce.md
>  auto res = map(exec,
Replace `map` by `grppi::map_reduce`.

2017-07-19 14:13 UTC, mdolz commented on doc/map-reduce.md
> +**map** and **reduce** stage, returning the reduced value.
Replace `stage` by `stages`.

2017-07-19 14:13 UTC, mdolz commented on doc/map-reduce.md
> +The only interface currently offered for this pattern is based in iterators
Replace `based in` by `based on`.

2017-07-19 14:13 UTC, mdolz commented on doc/map-reduce.md
> +    input data sequences, assuming that the size of all sequences are at least
Replace `are at least as` by `are, at least, as`.

2017-07-19 14:13 UTC, mdolz commented on doc/map-reduce.md
>  auto res = map(exec,
Replace `map` by `grppi::map_reduce`.

2017-07-19 14:13 UTC, mdolz commented on include/tbb/mapreduce.h
> +\tparam InputIt Iterator type used for input sequence.
Replace `for input` by `for the input`.

2017-07-19 14:13 UTC, mdolz commented on include/mapreduce.h
> - *	data section. Finaly all the thread section will be join in an output
Replace `Finaly` by `Finally`.
Replace `will be join` by `will be joined`.

2017-07-19 14:13 UTC, mdolz commented on include/seq/mapreduce.h
> +\tparam InputIt Iterator type used for input sequence.
Replace `for input` by `for the input`.

2017-07-19 14:13 UTC, mdolz commented on include/poly/mapreduce.h
> +\tparam InputIt Iterator type used for input sequence.
Replace `for input` by `for the input`.

2017-07-19 14:13 UTC, mdolz commented on include/native/mapreduce.h
> +\tparam InputIt Iterator type used for input sequence.
Replace `for input` by `for the input`.

2017-07-19 14:13 UTC, mdolz commented on doc/map-reduce.md
> +that, given inputs `x1, x2, ... , xN` of types `T1, T2, ... , TN` and an output
Replace `given inputs` by `given the inputs`.

2017-07-19 17:49 UTC, jdgarciauc3m commented on doc/map-reduce.md
> +extra optimizations.
Rephrased to:

However, **map/reduce** may fuse both stages, allowing for extra optimizations.

2017-07-19 17:49 UTC, jdgarciauc3m commented on doc/map-reduce.md
> +that, given inputs `x1, x2, ... , xN` of types `T1, T2, ... , TN` and an output
OK

2017-07-19 17:50 UTC, jdgarciauc3m commented on doc/map-reduce.md
>  auto res = map(exec,
OK

2017-07-19 17:50 UTC, jdgarciauc3m commented on doc/map-reduce.md
> +**map** and **reduce** stage, returning the reduced value.
OK

2017-07-19 17:54 UTC, jdgarciauc3m commented on doc/map-reduce.md
> +The only interface currently offered for this pattern is based in iterators
OK

2017-07-19 17:56 UTC, jdgarciauc3m commented on doc/map-reduce.md
> +    input data sequences, assuming that the size of all sequences are at least
Good catch!

2017-07-19 17:59 UTC, jdgarciauc3m commented on include/tbb/mapreduce.h
> +\tparam InputIt Iterator type used for input sequence.
OK

2017-07-19 18:00 UTC, jdgarciauc3m commented on include/seq/mapreduce.h
> +\tparam InputIt Iterator type used for input sequence.
OK

2017-07-19 18:01 UTC, jdgarciauc3m commented on include/poly/mapreduce.h
> +\tparam InputIt Iterator type used for input sequence.
OK

2017-07-19 18:02 UTC, jdgarciauc3m commented on include/native/mapreduce.h
> +\tparam InputIt Iterator type used for input sequence.
OK

2017-07-20 07:54 UTC, mdolz requested changes

2017-07-20 07:54 UTC, mdolz commented on doc/map-reduce.md
> +auto res = map_reduce(exec,
Replace `map_reduce` by `grppi::map_reduce`.

2017-07-20 07:59 UTC, Drioastorga submitted a review, later dismissed
Ok

2017-07-20 08:22 UTC, mdolz approved these changes

2017-07-20 09:07 UTC, javidoc00 approved these changes

2017-07-20 09:12 UTC, merged

2017-07-20 09:12 UTC, jdgarciauc3m commented
Closes issue #167