Added stream iteration unit test - issue 99
arcosuc3m/grppi pull request #251
Opened 2017-07-21 09:16 UTC by Drioastorga

I have added a unit test for the stream iteration.

2017-07-21 09:30 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  std::thread sink([&cons,&produced_queue](){
Rename sink->consumer

2017-07-21 09:30 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +template<typename Generator, typename Operation, typename Predicate, typename Consumer>
Rename Operation->Transformer

2017-07-21 09:31 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +    while(1){
for (;;)

2017-07-21 09:32 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  std::thread task([&generated_queue,&f,&condition,&produced_queue](){
Rename task->transformer_task

2017-07-21 09:32 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  std::thread prod([&gen, &generated_queue](){
Rename prod -> producer_task

2017-07-21 09:32 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  using produced_type = typename result_of<Operation(generated_value_type)>::type;
transformed_type

2017-07-21 09:33 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  mpmc_queue<std::experimental::optional<produced_type>> produced_queue{ex.queue_size,ex.lockfree};
At the begining of function put 

~~~c++
using namespace std::experimental
~~~

Then you simply use `optional<T>`

2017-07-21 09:34 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +      auto k = gen();
k -> item

2017-07-21 09:34 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +     produced_type val = *item;
~~~c++
auto val = *item;
~~~

2017-07-21 09:35 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +     do{
blank between do and open-brace

2017-07-21 09:35 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +     }while(condition(val));
Blank between close brace and `while`

2017-07-21 09:36 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +     produced_queue.push(std::experimental::optional<produced_type>{val});
No type qualifier needed here.

2017-07-21 09:37 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +void stream_iteration(parallel_execution_native &ex, Generator && gen, Operation && f, Predicate && condition, Consumer && cons){
argumentes names:
* `generate_op`
* `transform_op`
* `predicate_op`
* `consume_op`

2017-07-21 09:39 UTC, jdgarciauc3m commented on include/seq/stream_iteration.h
> +       auto val = *k;
k -> item

2017-07-21 09:40 UTC, jdgarciauc3m requested changes
See comments in code.

2017-07-21 10:12 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +template<typename Generator, typename Predicate, typename Consumer, typename ...Stages>
Stages -> MoreTransformers

2017-07-21 10:13 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  mpmc_queue< typename std::result_of<Generator()>::type > queue(ex.queue_size,ex.lockfree);
Factor-out  `generated_type`

2017-07-21 10:13 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  mpmc_queue< typename std::result_of<Generator()>::type > queue(ex.queue_size,ex.lockfree);
Use uniform initializer syntax.

2017-07-21 10:13 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  std::atomic<int> nend (0);
done_threads

2017-07-21 10:14 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  std::atomic<int> nend (0);
Uniform syntax.

2017-07-21 10:14 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  std::atomic<int> nelem (0);
Uniform syntax

2017-07-21 10:14 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  std::atomic<bool> send_finish( false );
Uniform syntax.

2017-07-21 10:16 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
>     for(;first!=end;first++) (*first).join();
Can be a range-based for loop.

2017-07-21 10:17 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
>     for(;first!=end;first++) (*first).join();
~~~c++
first->join()
~~~

2017-07-21 10:18 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  std::vector<std::thread> pipe_threads;
With 

~~~c++
using namespace std
~~~

explicit qualification is not needed

2017-07-21 10:18 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  composed_pipeline< mpmc_queue< typename std::result_of<Generator()>::type >, mpmc_queue< typename std::result_of<Generator()>::type >, 0, Stages ...>
Factor out typedefs with using

2017-07-21 10:18 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +    if(send_finish&&nelem==0){
~~~c++
if (send_finish && nelem==0) {
~~~

2017-07-21 10:19 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +      send_finish= false;
~~~c+++
send_finish = false;
~~~

2017-07-21 10:19 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +    if( !predicate_op(*item ) ) {
~~~c++
if (!predicate_op(*item )) {
~~~

2017-07-21 10:20 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +      consume_op( *item );
~~~c++
consume_op(*item);
~~~

2017-07-21 10:20 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +    }else queue.push( item );
~~~c++
} else queue.push(item);
~~~

2017-07-21 10:21 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +    auto item = queueOut.pop();
~~~c++
auto item{queueOut.pop()};
~~~

2017-07-21 10:22 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  mpmc_queue< typename std::result_of<Generator()>::type > queue(ex.queue_size,ex.lockfree);
queue -> generated_queue

2017-07-21 10:24 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +   mpmc_queue< typename std::result_of<Generator()>::type > queue(ex.queue_size,ex.lockfree);
generated_queue

2017-07-21 10:25 UTC, jdgarciauc3m requested changes
See comments

2017-07-21 10:56 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  mpmc_queue< generated_type > generated_queue{ex.queue_size,ex.lockfree};
~~~c++
mpmc_queue<generated_type>
~~~

2017-07-21 10:56 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  std::atomic<int> nelem {0};
nelem -> done_tasks

2017-07-21 10:56 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +      auto item = generate_op();
~~~c++
auto item{generate_op()};
~~~

2017-07-21 10:58 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +    (generated_queue, forward<pipeline_info<parallel_execution_native , MoreTransformers...> >(pipe) , transformed_queue, pipe_threads);
~~~c++
using pipeline_info_type = pipeline_info<parallel_execution_native , MoreTransformers...>;
~~~

2017-07-21 11:00 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +    }else queue.push(item);
~~~c++
} 
else {
  queue.push(item);
}

2017-07-21 11:01 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  mpmc_queue< generated_type > generated_queue{ex.queue_size,ex.lockfree};
~~~c++
mpmc_queue<generated_type> generated_queue{ex.queue_size,ex.lock_free};
~~~

2017-07-21 11:02 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  atomic<int> done_threads {0};
~~~c++
atomic<int> done_threads{0};
~~~

2017-07-21 11:04 UTC, jdgarciauc3m commented on include/native/stream_iteration.h
> +  for(auto && t : tasks) t.join();
for(auto && t : tasks) { t.join(); }

2017-07-21 11:05 UTC, jdgarciauc3m commented on unit_tests/stream_iteration.cpp
> +/*
Why is this comented out?

2017-07-21 11:05 UTC, jdgarciauc3m commented on unit_tests/stream_iteration.cpp
> +/*
Why is this comented out?

2017-07-21 11:06 UTC, jdgarciauc3m commented on unit_tests/stream_iteration.cpp
> +/*
Why is this comented out?

2017-07-21 11:06 UTC, jdgarciauc3m commented on include/seq/stream_iteration.h
> +template<typename Generator, typename Predicate, typename Consumer, typename ...Stages>
doxygen?

2017-07-21 11:06 UTC, jdgarciauc3m commented on include/seq/stream_iteration.h
> +template<typename Generator, typename Predicate, typename Consumer, typename ...Stages>
doxygen?

2017-07-21 11:07 UTC, jdgarciauc3m commented on include/seq/stream_iteration.h
> +template<typename Generator, typename Transformer, typename Predicate, typename Consumer>
doxygen?

2017-07-21 11:07 UTC, jdgarciauc3m commented on include/seq/stream_iteration.h
> +template<typename Generator, typename Transformer, typename Predicate, typename Consumer>
doxygen?

2017-07-21 11:07 UTC, jdgarciauc3m commented on include/seq/stream_iteration.h
> +template<typename Generator, typename Transformer, typename Predicate, typename Consumer>
doxygen?

2017-07-21 11:08 UTC, Drioastorga commented on unit_tests/stream_iteration.cpp
> +/*
This is commented because de polymorphic has not the stream iteration implemented yet.

2017-07-21 11:08 UTC, jdgarciauc3m requested changes
More comments to address...

2017-07-24 13:44 UTC, jdgarciauc3m requested changes
poly/stream_iteration.h needs to be revised to select only between sequential and native implementations.

Tests should be revised to include testing of poly stream_iteration.

2017-07-25 14:13 UTC, Drioastorga commented
I have solved the issue and now the stream iteration polymorphic execution version can be composed with farm and pipeline ,and the unit test covers it.

2017-07-25 14:23 UTC, jdgarciauc3m commented
The following tests FAILED:
	 33 - stream_iteration_test/*.static_composed_pipeline (OTHER_FAULT)
	 34 - stream_iteration_test/*.poly_composed_pipeline (OTHER_FAULT)
	 75 - composed_reduce_test/*.static_window_offset (Failed)
	 76 - composed_reduce_test/*.static_offset_window (Failed)

2017-07-25 15:08 UTC, Drioastorga commented
Fixed.

2017-07-25 16:28 UTC, jdgarciauc3m approved these changes
OK

2017-07-25 16:28 UTC, merged

2017-07-25 16:28 UTC, jdgarciauc3m commented
Closes issue #99