Added support for context
arcosuc3m/grppi pull request #304
Opened 2018-01-22 09:06 UTC by Drioastorga

Added support for context.

Current version allows to switch context between omp, native and sequential back-ends. Using TBB as back-end uses sequential implementation.

2018-01-23 10:52 UTC, jdgarciauc3m requested changes
Address coments

2018-01-23 10:52 UTC, jdgarciauc3m commented on include/common/context.h
> +\brief Representation of farm pattern.
Wrong documentation

2018-01-23 10:52 UTC, jdgarciauc3m commented on include/common/context.h
> +  int cardinality_;
Probably this member variable is not needed. Isn't it?

2018-01-23 10:52 UTC, jdgarciauc3m commented on include/context.h
> +auto context(ExecutionPolicy & ex, Transformer && transform_op)
Find a better name.
Candidates: `run`, `run_with`, `run_at`

2018-01-24 09:39 UTC, Drioastorga commented
Renamed context interface to 'run_with'. 
Reviewed documentation.

2018-02-03 11:26 UTC, jdgarciauc3m approved these changes
OK. But I need to add some example application. To be handled as separate issue.

2018-02-03 11:26 UTC, merged