Added unit tests for context - Issue 307
arcosuc3m/grppi pull request #308
Opened 2018-01-25 09:47 UTC by Drioastorga

Added unit test for the context pattern.
Fixed some minor bugs in the context implementation in sequential, native and openmp back-ends.

2018-02-03 11:38 UTC, jdgarciauc3m requested changes
This pull request has conflicts with master.

Please solve them.

2018-02-07 14:20 UTC, jdgarciauc3m requested changes
Please, address comments.

2018-02-07 14:20 UTC, jdgarciauc3m commented on include/seq/sequential_execution.h
> +    std::cout<<"PUSH END"<<std::endl;
You probably do not want to do this.

2018-02-07 15:36 UTC, Drioastorga commented
Fixed.

2018-02-07 16:01 UTC, jdgarciauc3m approved these changes

2018-02-07 16:01 UTC, merged