Added sqrinv_seq_farm_pipe example - Issue 313
arcosuc3m/grppi pull request #344
Opened 2018-03-05 09:13 UTC by mdolz

Added sqrinv_seq example using the farm+pipeline composition.

2018-03-05 22:17 UTC, jdgarciauc3m requested changes
We should not depend on Boost

2018-03-05 22:17 UTC, jdgarciauc3m commented on samples/farm/farm_pipeline/CMakeLists.txt
> +  ${Boost_LIBRARIES} )
Why boost?

2018-03-06 07:13 UTC, mdolz commented
Fixed.

2018-03-06 22:51 UTC, jdgarciauc3m approved these changes
OK.

2018-03-06 22:51 UTC, merged

2018-03-06 22:52 UTC, jdgarciauc3m commented
This solves issue #313