Removed logging from unit test
arcosuc3m/grppi pull request #346
Opened 2018-03-06 16:39 UTC by javidoc00

2018-03-06 22:58 UTC, jdgarciauc3m requested changes
Remove commented logging lines.

2018-03-06 22:58 UTC, jdgarciauc3m commented on include/omp/parallel_execution_omp.h
> +      //std::cerr << "Processing: <" << *item.first << " , " << item.second << ">\n";
This should not be commented but removed!

2018-03-07 10:17 UTC, javidoc00 commented
removed commented lines

2018-03-07 19:05 UTC, jdgarciauc3m approved these changes
OK. Thanks!

2018-03-07 19:07 UTC, merged

2018-03-07 19:08 UTC, jdgarciauc3m commented
This solves issue #335